{
 "title": "Vintage Story Logs",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "query": "serverstats" },
   { "name": "player", "query": "propaneko" }
  ]
 },
 "panels": [
  {
   "title": "Blocks broken",
   "type": "xychart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `DidBreakBlock` |= `${player}`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Blocks placement",
   "type": "xychart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `DidPlaceBlock` |= `${player}`"
    }
   ]
  },
  {
   "title": "Movements",
   "type": "xychart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `PlayerCoords` |= `${player}`"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `${player}` |= ``",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Death",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"vsserver\"} |= `Death` |= `${player}` [$__auto])"
    }
   ]
  },
  {
   "title": "Blocks broken",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"vsserver\"} |= `DidBreakBlock` |= `${player}` [$__auto])"
    }
   ]
  },
  {
   "title": "Blocks placement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"vsserver\"} |= `DidPlaceBlock` |= `${player}` [$__auto])"
    }
   ]
  }
 ]
}